{
    "version": "0.2",
    "phases": {
        "pre_build": {
            "commands": [
                "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 175747436878.dkr.ecr.us-east-1.amazonaws.com",
                "echo $CODEBUILD_RESOLVED_SOURCE_VERSION",
                "echo $HASH_FROM_SOURCE",
                "COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)",
                "IMAGE_TAG=${COMMIT_HASH:=latest}"
            ]
        }
    }
}
