version: 0.2
phases:
  install:
    commands:
      - echo Entered the install phase...
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
  pre_build:
    commands:
      - echo Entered the pre_build phase...
     
    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
