{
    "version": "0.2",
    "phases": {
        "pre_build": {
            "commands": [
                "cat passedvariable.json | jq '.passedvar'",
                "source variable.sh",
                "echo $CODEBUILD_RESOLVED_SOURCE_VERSION"
            ]
        }
    }
}
